name: Java CI/CD with Gradle

on:
  pull_request:
    branches: [ "cicd-test" ]
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make application.properties & yml
        run: |
          mkdir ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Make SSL keystore
        run: echo "${{ secrets.SSL_KEYSTORE }}" | base64 --decode > ./src/main/resources/keystore.p12

      - name: Clean bootJar
        run: ./gradlew clean bootJar

      - name: Docker login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }} .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} <<EOF
          sudo docker stop ${{ secrets.DOCKER_IMAGE }}
          sudo docker rm ${{ secrets.DOCKER_IMAGE }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
          sudo docker run -d --name ${{ secrets.DOCKER_IMAGE }} -p 443:443 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
          EOF
